version: 0.2
 
phases:
  install:
    runtime-versions:
      nodejs: '16'
  pre_build:
    commands:
      - cd backend
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Running build...
      - npm run build
  post_build:
    commands:
      - cp -R node_modules/ dist/node_modules # nodejs needs this
      - cp Procfile dist/Procfile # EBS needs this
      - echo Build completed on `date`
 
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: dist